package com.go.notification.utils;

public enum JedisEnum {

	UNREADCOUNT, USERPRESENCE , RECENTCONVERSATIONINVITE , RECENTDMINVITE , LASTREADMESSAGEID , ACTIVECONVERSATION , NOTIFICATION ,
	TTL ,

}
